services:
  app:
    image: miniwebapp/app:latest
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
